[package]
name = "app"
version = "0.1.0"
authors = ["tyanboot <tyanboot@outlook.com>"]
edition = "2018"

[dependencies]
warp = "0.2"
thiserror = "1.0"
tokio = { version = "0.2", features = ["macros"] }
macros = { path = "../macros" }
env_logger = "0.8.2"